Controllers/DashboardController.cs
using KidKinder.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting;
using System.Web;
using System.Web.Mvc;

namespace KidKinder.Controllers
{
    public class DashboardController : Controller
    {
        KidKinderContext context = new KidKinderContext();
        public ActionResult Index()
        {
            //Branşı resim olan öğretmen sayısı

            int branchId = context.Branches.Where(x => x.Name == "Resim").Select(y => y.BranchId).FirstOrDefault();
            int res = context.Teachers.Where(x => x.BranchId == branchId).Count();
            ViewBag.resimTeacherCount = res;
            //Eğitimlerin orlama ücreti
            ViewBag.avgClassroomPrice = context.ClassRooms.Average(x => x.Price).ToString("0.00");

            //Toplam Öğretmen Sayısı
            int teacherCount = context.Teachers.Count();
            int tec = teacherCount;
            ViewBag.teacherCount = teacherCount;

            //Müzik
            int branchId1 = context.Branches.Where(x => x.Name == "Müzik").Select(y => y.BranchId).FirstOrDefault();

            int muz = context.Teachers.Where(x => x.BranchId == branchId1).Count();
            ViewBag.muzikTeacherCount = muz;
            //Matematik
            int branchId2 = context.Branches.Where(x => x.Name == "Matematik").Select(y => y.BranchId).FirstOrDefault();
            int mat = context.Teachers.Where(x => x.BranchId == branchId2).Count();
            ViewBag.matTeacherCount = mat;
            //İspanyolca
            int branchId3 = context.Branches.Where(x => x.Name == "İspanyolca").Select(y => y.BranchId).FirstOrDefault();
            int isp = context.Teachers.Where(x => x.BranchId == branchId3).Count();
            ViewBag.ispTeacherCount = isp;
            //Edebiyat
            int branchId4 = context.Branches.Where(x => x.Name == "Edebiyat").Select(y => y.BranchId).FirstOrDefault();
            int edb = context.Teachers.Where(x => x.BranchId == branchId4).Count();
            ViewBag.edTeacherCount = edb;

            //google chart
            ViewBag.edb = (decimal)(edb / tec);
            ViewBag.isp = (decimal)(isp / tec);
            ViewBag.mat = (decimal)(mat / tec);
            ViewBag.muz = (decimal)(muz / tec);
            ViewBag.res = (decimal)(res / tec);

            //Gelen Mesaj Sayısı
            ViewBag.mesageCount = context.Contacts.Count();

            //Sınıf Sayısı
            ViewBag.sinifCount = context.ClassRooms.Count();

            //Referans Sayısı
            ViewBag.refCount = context.Testimonials.Count();

            //Mail listesi abone sayısı

            ViewBag.newsletter = context.MailSubscribes.Count();

            //Enyüksek Ücretli kurs Fiyatı
            ViewBag.coursePrice = context.ClassRooms.OrderBy(x => x.Price).First().Price.ToString("0.00");


            //Enyüksek Ücretli kurs Adı
            ViewBag.coursePriceCource = context.ClassRooms.OrderBy(x => x.Price).First().Title;



            return View();
        }
        public PartialViewResult PartialTecherList()
        {
            var values = context.Teachers.OrderByDescending(x => x.TeacherId).Take(4).ToList();
            return PartialView(values);
        }
    }
}

Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}
<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    google.charts.load('current', { packages: ['corechart'] });
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        // Define the chart to be drawn.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Element');
        data.addColumn('number', 'Percentage');
        data.addRows([
            ['Matematik', 0.38],
            ['Resim', 0.21],
            ['Müzik', 0.11],
            ['İspanyolca', 0.19],
            ['Edebiyat', 0.11]
        ]);
        // Instantiate and draw the chart.
        var chart = new google.visualization.PieChart(document.getElementById('myPieChart'));
        chart.draw(data, null);
    }
</script>
<link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/css/font-awesome-n.min.css">

<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-xl-4 col-md-12">
                        <div class="card mat-stat-card">
                            <div class="card-block">
                                <div class="row align-items-center b-b-default">
                                    <div class="col-sm-6 b-r-default p-b-20 p-t-20">
                                        <div class="row align-items-center text-center">
                                            <div class="col-4 p-r-0">
                                                <i class="far fa-user text-c-purple f-24"></i>
                                            </div>
                                            <div class="col-8 p-l-0">
                                                <h5>@ViewBag.resimTeacherCount</h5>
                                                <p class="text-muted m-b-0">Resim Öğretmeni</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 p-b-20 p-t-20">
                                        <div class="row align-items-center text-center">
                                            <div class="col-4 p-r-0">
                                                <i class="fas fa-volume-down text-c-green f-24"></i>
                                            </div>
                                            <div class="col-8 p-l-0">
                                                <h5>5</h5>
                                                <p class="text-muted m-b-0">Sınıf Sayısı</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row align-items-center">
                                    <div class="col-sm-6 p-b-20 p-t-20 b-r-default">
                                        <div class="row align-items-center text-center">
                                            <div class="col-4 p-r-0">
                                                <i class="far fa-file-alt text-c-red f-24"></i>
                                            </div>
                                            <div class="col-8 p-l-0">
                                                <h5>
                                                    ₺ @ViewBag.avgClassroomPrice

                                                </h5>
                                                <p class="text-muted m-b-0">Ortalama Fiyat</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 p-b-20 p-t-20">
                                        <div class="row align-items-center text-center">
                                            <div class="col-4 p-r-0">
                                                <i class="far fa-envelope-open text-c-blue f-24"></i>
                                            </div>
                                            <div class="col-8 p-l-0">
                                                <h5>12</h5>
                                                <p class="text-muted m-b-0">Mesaj</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-12">
                        <div class="card mat-clr-stat-card text-white red ">
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-3 text-center bg-c-red">
                                        <i class="fas fa-star mat-icon f-24"></i>
                                    </div>
                                    <div class="col-9 cst-cont">
                                        <h5>@ViewBag.edTeacherCount</h5>
                                        <p class="m-b-0">Edebiyat Öğretmeni</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card mat-clr-stat-card text-white green">
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-3 text-center bg-c-green">
                                        <i class="fas fa-trophy mat-icon f-24"></i>
                                    </div>
                                    <div class="col-9 cst-cont">
                                        <h5>@ViewBag.resimTeacherCount</h5>
                                        <p class="m-b-0">Resim Öğretmeni</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-12">
                        <div class="card mat-clr-stat-card text-white green ">
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-3 text-center bg-c-green">
                                        <i class="fas fa-star mat-icon f-24"></i>
                                    </div>
                                    <div class="col-9 cst-cont">
                                        <h5>@ViewBag.matTeacherCount</h5>
                                        <p class="m-b-0">Matematik Öğretmeni</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card mat-clr-stat-card text-white blue">
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-3 text-center bg-c-blue">
                                        <i class="fas fa-trophy mat-icon f-24"></i>
                                    </div>
                                    <div class="col-9 cst-cont">
                                        <h5>@ViewBag.ispTeacherCount</h5>
                                        <p class="m-b-0">İspanyolca Öğretmeni</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Material statustic card end -->
                    <!-- order-visitor start -->
                    <!-- order-visitor end -->
                    <!--  sale analytics start -->
                    @Html.Action("PartialTecherList", "Dashboard")
                    <div class="col-xl-6 col-md-12">
                        <div class="row">
                            <!-- sale card start -->

                            <div class="col-md-6">
                                <div class="card text-center order-visitor-card">
                                    <div class="card-block">
                                        <h6 class="m-b-0">Gelen Mesaj Sayısı</h6>
                                        <h4 class="m-t-15 m-b-15"><i class="fa fa-arrow-down m-r-15 text-c-red"></i>@ViewBag.mesageCount</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card text-center order-visitor-card">
                                    <div class="card-block">
                                        <h6 class="m-b-0">Sınıf Sayısı</h6>
                                        <h4 class="m-t-15 m-b-15"><i class="fa fa-arrow-up m-r-15 text-c-green"></i> @ViewBag.sinifCount</h4>

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card bg-c-red total-card">
                                    <div class="card-block">
                                        <div class="text-left">
                                            <h4>@ViewBag.refCount</h4>
                                            <p class="m-0">Referans sayısı</p>
                                        </div>
                                        <span class="label bg-c-red value-badges">15%</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card bg-c-green total-card">
                                    <div class="card-block">
                                        <div class="text-left">
                                            <h4>@ViewBag.newsletter</h4>
                                            <p class="m-0">Mail Listesi Abone</p>
                                        </div>
                                        <span class="label bg-c-green value-badges">20%</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card text-center order-visitor-card">
                                    <div class="card-block">
                                        <h6 class="m-b-0">En Yüksek Ücretli Kurs Fiyatı</h6>
                                        <h4 class="m-t-15 m-b-15">₺ @ViewBag.coursePrice</h4>
                                        <p class="m-b-0">36% From Last 6 Months</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card text-center order-visitor-card">
                                    <div class="card-block">
                                        <h6 class="m-b-0">En Yüksek Ücretli Kurs</h6>
                                        <h4 class="m-t-15 m-b-15">@ViewBag.coursePriceCource</h4>
                                
                                    </div>
                                </div>
                            </div>
                            <!-- sale card end -->
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@*@ViewBag.edb
@ViewBag.isp
@ViewBag.mat
@ViewBag.muz
@ViewBag.res*@
<div class="container">
    <h3>Öğretmenlerin Branşlara Göre Dağılımı</h3>
    <br />
    <div id="myPieChart" />
</div>

Views/Dashboard/PartialTecherList.cshtml
@model List<KidKinder.Entities.Teacher>

<div class="col-xl-6 col-md-12">
    <div class="card table-card">
        <div class="card-header">
            <h5>Son eklenen öğretmenler</h5>
            <div class="card-header-right">
                <ul class="list-unstyled card-option">
                    <li><i class="fa fa fa-wrench open-card-option"></i></li>
                    <li><i class="fa fa-window-maximize full-card"></i></li>
                    <li><i class="fa fa-minus minimize-card"></i></li>
                    <li><i class="fa fa-refresh reload-card"></i></li>
                    <li><i class="fa fa-trash close-card"></i></li>
                </ul>
            </div>
        </div>
        <div class="card-block">
            <div class="table-responsive">
                <table class="table table-hover m-b-0 without-header">
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="d-inline-block align-middle">
                                        <img src="@item.ImageUrl" alt="user image" class="img-radius img-40 align-top m-r-15">
                                        <div class="d-inline-block">
                                            <h6>@item.NameSurname</h6>
                                            <p class="text-muted m-b-0">@item.Branch.Name</p>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>