Controllers/AdminLayoutController.cs
using KidKinder.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KidKinder.Controllers
{
    public class AdminLayoutController : Controller
    {
        KidKinderContext context = new KidKinderContext();
        // GET: AdminLayout
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialPreLoader()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavBar()
        {
            return PartialView();
        }
        public PartialViewResult PartialNotification()
        {
            var values = context.Notifications.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialNavBarProfileHeader()
        {
            return PartialView();
        }
        public PartialViewResult PartialSideBar()
        {
            return PartialView();
        }

        public PartialViewResult PartialScripts()
        {
            return PartialView();
        }
        public PartialViewResult PartialSubHeader()
        {
            return PartialView();
        }
    }
}

Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead", "AdminLayout")

<body>
    <!-- Pre-loader start -->
    @Html.Action("PartialPreLoader", "AdminLayout")

    <!-- Pre-loader end -->
    <div id="pcoded" class="pcoded">
        <div class="pcoded-overlay-box"></div>
        <div class="pcoded-container navbar-wrapper">
            @Html.Action("PartialNavBar", "AdminLayout")

            <div class="pcoded-main-container">

                <div class="pcoded-wrapper">
                    @Html.Action("PartialSideBar", "AdminLayout")
                    <div class="pcoded-content">
                        @Html.Action("PartialSubHeader", "AdminLayout")
                        @RenderBody()
                        <!--<div class="pcoded-inner-content">-->
                        <!-- Main-body start -->
                        <!--<div class="main-body">
    <div class="page-wrapper">-->
                        <!-- Page-body start -->
                        <!--<div class="page-body">
                    <div class="card pt-5 pb-5">

                    </div>
                </div>
            </div>
        </div>
    </div>-->
                    </div>
                    <div id="styleSelector"></div>
                </div>
            </div>
        </div>
    </div>

    @Html.Action("PartialScripts", "AdminLayout")
</body>

</html>

Views/AdminLayout/PartialHead.cshtml
<head>
    <title>Kid Kinder Admin Paneli</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="keywords" content="flat ui, admin Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="Codedthemes" />
    <!-- Favicon icon -->
    <link rel="icon" href="~/Templates/material_able-main/assets/images/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/css/bootstrap/css/bootstrap.min.css">
    <!-- waves.css -->
    <link rel="stylesheet" href="~/Templates/material_able-main/assets/pages/waves/css/waves.min.css" type="text/css" media="all">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/icon/themify-icons/themify-icons.css">
    <!-- feather icon -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/icon/feather/css/feather.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/icon/font-awesome/css/font-awesome.min.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/Templates/material_able-main/assets/css/jquery.mCustomScrollbar.css">
</head>

Views/AdminLayout/PartialNavBar.cshtml
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">
        <div class="navbar-logo">
            <a class="mobile-menu waves-effect waves-light" id="mobile-collapse" href="#!">
                <i class="ti-menu"></i>
            </a>
            <div class="mobile-search waves-effect waves-light">
                <div class="header-search">
                    <div class="main-search morphsearch-search">
                        <div class="input-group">
                            <span class="input-group-prepend search-close"><i class="ti-close input-group-text"></i></span>
                            <input type="text" class="form-control" placeholder="Enter Keyword">
                            <span class="input-group-append search-btn"><i class="ti-search input-group-text"></i></span>
                        </div>
                    </div>
                </div>
            </div>
            <a href="index.html">
                <img class="img-fluid" src="~/Templates/material_able-main/assets/images/kids.png" alt="Theme-Logo" style="width:100px;" />
            </a>
            <a class="mobile-options waves-effect waves-light">
                <i class="ti-more"></i>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <ul class="nav-left">
                <li>
                    <div class="sidebar_toggle"><a href="javascript:void(0)"><i class="ti-menu"></i></a></div>
                </li>
                <li>
                    <a href="#!" onclick="javascript:toggleFullScreen()" class="waves-effect waves-light">
                        <i class="ti-fullscreen"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                @Html.Action("PartialNotification","AdminLayout")
                @Html.Action("PartialNavBarProfileHeader", "AdminLayout")
              
               
            </ul>
        </div>
    </div>
</nav>

Views/AdminLayout/PartialNavBarProfileHeader.cshtml
<li class="user-profile header-notification">
    <a href="#!" class="waves-effect waves-light">
        <img src="~/Templates/material_able-main/assets/images/avatar-4.jpg" class="img-radius" alt="User-Profile-Image">
        <span>Admin</span>
        <i class="ti-angle-down"></i>
    </a>
    <ul class="show-notification profile-notification">
        <li class="waves-effect waves-light">
            <a href="#!">
                <i class="ti-settings"></i> Ayarlar
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="user-profile.html">
                <i class="ti-user"></i> Profil
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="email-inbox.html">
                <i class="ti-email"></i> Mesajlarım
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="auth-lock-screen.html">
                <i class="ti-lock"></i> Ekranı Kilitle
            </a>
        </li>
        <li class="waves-effect waves-light">
            <a href="/Login/Logout/">
                <i class="ti-layout-sidebar-left"></i> Çıkış Yap
            </a>
        </li>
    </ul>
</li>

Views/AdminLayout/PartialNotification.cshtml
@model List<KidKinder.Entities.Notification>

<li class="header-notification">
    <a href="#!" class="waves-effect waves-light">
        <i class="ti-bell"></i>
        <span class="badge bg-c-red"></span>
    </a>
    <ul class="show-notification">
        <li>
            <h6>Bildirimler</h6>
            <label class="label label-danger">New</label>
        </li>
        @foreach (var item in Model)
        {
            <li class="waves-effect waves-light">
                <div class="media">
                    <img class="d-flex align-self-center img-radius" src="@item.ImageUrl" alt="Generic placeholder image">
                    <div class="media-body">
                        <h5 class="notification-user">@item.Title</h5>
                        <p class="notification-msg">@item.Description</p>
                        <span class="notification-time">@item.NotificationDate.ToString("dd MMMMM yyyy")</span>
                    </div>
                </div>
            </li>
        }
    </ul>
</li>

Views/AdminLayout/PartialPreLoader.cshtml
<div class="theme-loader">
    <div class="loader-track">
        <div class="preloader-wrapper">
            <div class="spinner-layer spinner-blue">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
            <div class="spinner-layer spinner-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
            <div class="spinner-layer spinner-yellow">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
            <div class="spinner-layer spinner-green">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/AdminLayout/PartialScripts.cshtml
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/jquery/jquery.min.js "></script>
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/jquery-ui/jquery-ui.min.js "></script>
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/popper.js/popper.min.js"></script>
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/bootstrap/js/bootstrap.min.js "></script>
<!-- waves js -->
<script src="~/Templates/material_able-main/assets/pages/waves/js/waves.min.js"></script>
<!-- jquery slimscroll js -->
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/jquery-slimscroll/jquery.slimscroll.js"></script>
<script src="~/Templates/material_able-main/assets/js/pcoded.min.js"></script>
<script src="~/Templates/material_able-main/assets/js/vertical/vertical-layout.min.js"></script>
<script src="~/Templates/material_able-main/assets/js/jquery.mCustomScrollbar.concat.min.js"></script>
<!-- Custom js -->
<script type="text/javascript" src="~/Templates/material_able-main/assets/js/script.min.js"></script>

Views/AdminLayout/PartialSideBar.cshtml
<nav class="pcoded-navbar">
    <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
    <div class="pcoded-inner-navbar main-menu">
        <div class="">
            <div class="main-menu-header">
                <img class="img-80 img-radius" src="~/Templates/material_able-main/assets/images/avatar-4.jpg" alt="User-Profile-Image">
                <div class="user-details">
                    <span id="more-details">Kid Kinder Admin</span>
                </div>
            </div>
        </div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="">
                <a href="/Dashboard/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-home"></i></span>
                    <span class="pcoded-mtext">Dashboard</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminService/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-server"></i><b>D</b></span>
                    <span class="pcoded-mtext">Hizmetler</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminAbout/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-agenda"></i><b>D</b></span>
                    <span class="pcoded-mtext">Hakkıımızda</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminAboutList/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-alarm-clock"></i><b>D</b></span>
                    <span class="pcoded-mtext">Hakkıımızda Liste</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminAdress/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-anchor"></i><b>D</b></span>
                    <span class="pcoded-mtext">Adres</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminBranch/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-brush"></i><b>D</b></span>
                    <span class="pcoded-mtext">Branşlar</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminContact/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-comment"></i><b>D</b></span>
                    <span class="pcoded-mtext">Mesajlar</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminFeature/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-direction-alt"></i><b>D</b></span>
                    <span class="pcoded-mtext">Feature</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminMailSubscribe/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-eye"></i><b>D</b></span>
                    <span class="pcoded-mtext">Mail Bülteni</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminTestimonial/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-css3"></i><b>D</b></span>
                    <span class="pcoded-mtext">Referanslar</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminClass/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-clip"></i><b>D</b></span>
                    <span class="pcoded-mtext">Sınıflar</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminGallery/Index/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-gallery"></i><b>D</b></span>
                    <span class="pcoded-mtext">Galeri</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="">
                <a href="/AdminTeacher/TeacherList/" class="waves-effect waves-dark">
                    <span class="pcoded-micon"><i class="ti-user"></i><b>D</b></span>
                    <span class="pcoded-mtext">Öğretmenler</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
        </ul>
    </div>
</nav>

Views/AdminLayout/PartialSubHeader.cshtml
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h5 class="m-b-10">Kidkinder Admin Paneli</h5>
                    <p class="m-b-0">Uygulamanın yeni veri girişi, güncelleme, silme ve diğer işlemlerin yapıldığı sayfadır.</p>
                </div>
            </div>
            <div class="col-md-4">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/Dashboard/Index/"> <i class="fa fa-home"></i> </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>